### ISSUE TITLE
GeoIP2 licensing issues

### ISSUE THREAD

**Issue by lokkju** [blockpane/cosmissed#5]
I read your notice on the README, and checked out the code; Why not embed the GeoLite2 database (in CSV format or via MMDB with a WASM compiled libmaxminddb) within the project rather than using the API? From what I know, MaxMind allows GeoLite2 redistribution as long as you provide attribution; alternatively, there are many project on github that repackage the data in various ways and make it available for download - you could simply download and cache it during the build process.

GeoLite2 only has city/state/country, but that seems to be all you're really using here.

**Comment by blockpane** [comment]
I originally was using the database file. Unfortunately the EULA is pretty clear that providing a public service that uses the database requires a subscription and the cost for the API is substantially cheaper than buying a license for the database. I have this running on 5 chains and it costs almost nothing because of it caches the data. I think it's cost about $3USD in roughly 6 months.

**Comment by lokkju** [comment]
I'm really curious where in the EULA you see that, as that's not their own understanding:

"The GeoLite2 End User License Agreement also allows you to use data from GeoLite2 databases and web services to build applications that are available to users outside your company or organization, or to display that data to users outside your organization, as long as you attribute the data to MaxMind."

https://support.maxmind.com/hc/en-us/articles/4408936690075-Sell-or-Display-Data-from-GeoLite2-Databases-and-Web-Services

**Comment by blockpane** [comment]
You are 100% correct, but the app is using more than what is provided in the free dataset. I wanted to display ISP information because I felt was important to see network centralization. In that specific case the GeoIP2 City+ information cannot be used for public consumption without a commercial site license and that costs quite a bit. Even just the regular City database has a $100/month price tag.

**Comment by lokkju** [comment]
And that makes complete sense. Thank you for taking the time to provide a fuller explanation.
